// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_NOTIFICATIONS = 'SET_USER_NOTIFICATIONS';
export const SET_USER_FRIENDS = 'SET_USER_FRIENDS';
export const SET_USER_PRIVATE_CHANNELS = 'SET_USER_PRIVATE_CHANNELS';
export const SET_USER_CLASS_ROOMS = 'SET_USER_CLASS_ROOMS';
export const SET_TEACHER = 'SET_TEACHER';
// CHANNELS
export const SET_CHANNELS = 'SET_CHANNELS';
export const CLEAR_CHANNELS = 'CLEAR_CHANNELS';
// SELECTED CHANNEL
export const SET_SELECTED_CHANNEL = 'SET_SELECTED_CHANNEL';
export const CLEAR_SELECTED_CHANNEL = 'CLEAR_SELECTED_CHANNEL';
export const SET_IS_PRIVATE = 'SET_IS_PRIVATE';
export const SET_IS_CLASS_ROOM = 'SET_IS_CLASS_ROOM';
// MESSAGES
export const SET_MESSAGES_LOADING = 'SET_MESSAGES_LOADING';
export const SET_INITIAL_MESSAGES = 'SET_INITIAL_MESSAGES';
export const SHIFT_MESSAGE_PAGE = 'SHIFT_MESSAGE_PAGE';
export const CONCAT_MESSAGE = 'CONCAT_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
// UI
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SET_MOBILE = 'SET_MOBILE';
export const SET_NOT_MOBILE = 'SET_NOT_MOBILE';
export const SET_ACCOUNT_DRAWER_OPEN = 'SET_ACCOUNT_DRAWER_OPEN';
export const SET_ACCOUNT_DRAWER_CLOSE = 'SET_ACCOUNT_DRAWER_CLOSE';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_USER_URL = 'SET_USER_URL';
// CACHE
export const ADD_CACHED_USER = 'ADD_CACHED_USER';
export const SET_FRIEND_REQUEST_PENDING = 'SET_FRIEND_REQUEST_PENDING';
export const ADD_FRIEND_STATUS = 'ADD_FRIEND_STATUS';
export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
